usfedgov_google_analytics.settings:
  type: mapping
  label: Settings
  mapping:
    usfedgov_google_analytics__load_from_cdn:
      type: boolean
    usfedgov_google_analytics__disable:
      type: boolean
    usfedgov_google_analytics__load_minified:
      type: boolean
    usfedgov_google_analytics__settings:
      type: mapping
      mapping:
        agency:
          type: string
        subagency:
          type: string
        extra:
          type: mapping
          mapping:
            sp:
              type: string
            exts:
              type: string
            yt:
              type: boolean
            sdor:
              type: boolean
            dclink:
              type: boolean
            aip:
              type: boolean
            pua:
              type: string
            enhlink:
              type: boolean
            autotracker:
              type: boolean
            forcessl:
              type: boolean
            optout:
              type: boolean
            fedagencydim:
              type: string
            fedsubagencydim:
              type: string
            fedversiondim:
              type: string
            palagencydim:
              type: string
            palsubagencydim:
              type: string
            palversiondim:
              type: string
            maincd:
              type: boolean
            parallelcd:
              type: boolean
            cto:
              type: string
          
